# ============================================================
# Configuration file for the multi_layer model using Basilisk
#
#
#
#
# ============================================================
#
# INITIAL CONDITION
#
P = 0.04        # energy level (estimated so that kpHs is reasonable)
coeff_kpL0 = 10 # kpL0 = coeff_kpL0 * pi
N_mode = 32     # number of nodes
N_power = 5     # directional spreading coeff
F_shape = 'PM'  # shape of the initial spectrum

#
# DOMAIN DEFINITION
#
N_grid = 6   # 1024=10 2^N_grid, number of x and y gridpoints
L = 200.0    # domain size
N_layer = 16 # number of layers
h0 = 50.0    # depth of water (m)

#
# RUN PARAMETERS
#
tend = 5.0                  # (s) time to end the simu
file_out = 'out.nc'         # name of output file
dtout = 1.0                 # dt for output in netcdf
restart = 0
file_restart = 'restart.nc' # name of restart file if restart=true


#
# SOLVER PARAMETERS
#
nu0 = 0.000025 # m2 s-2 Viscosity for vertical diffusion
RANDOM = 6     # random integer (>1) for random number generator
thetaH = 0.5   # theta_h for dumping fast barotropic modes
